### ISSUE TITLE
zoomeye scan not work

### ISSUE THREAD

**Issue by lolminerxmrig** [xzajyjs/ThunderSearch#20]
hi.
zoomeye scan not work

![image](https://github.com/xzajyjs/ThunderSearch/assets/108659226/53cf5840-4116-4f08-927e-8913bd7c6ef3)

**Comment by xzajyjs** [comment]
Please clone the repository and use `python3 ThunderSearch.py` to run the program and copy the error message (if any) output by the console.

**Comment by lolminerxmrig** [comment]
![image](https://github.com/xzajyjs/ThunderSearch/assets/108659226/0166e9b8-e491-4a3d-84d9-7091245fe9d5)

![image](https://github.com/xzajyjs/ThunderSearch/assets/108659226/3bfc2606-7755-4b32-a46c-151c11b36ba8)

**Comment by lolminerxmrig** [comment]
ThunderSearch.py
rm: cannot remove 'zoomeye_access_token.txt': No such file or directory
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Desktop\search-main\1\ThunderSearch.py", line 890, in run
    with open(self.FILE.get(), "w", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by xzajyjs** [comment]
use the release exe.

**Comment by lolminerxmrig** [comment]
> use the release exe.

Plz add link

**Comment by xzajyjs** [comment]
https://github.com/xzajyjs/ThunderSearch/releases/tag/v2.5.1
