### ISSUE TITLE
win11无法打开

### ISSUE THREAD

**Issue by Ludovicofu** [xzajyjs/ThunderSearch#21]
解压后直接打开，报错
![image](https://github.com/xzajyjs/ThunderSearch/assets/91811209/d5d3ae0c-0677-4dc7-8cd6-85a021822c66)
2.3版本的可以正常打开

**Comment by xzajyjs** [comment]
请提供全部Traceback信息。
并clone仓库后尝试使用`python3 ThunderSearch.py`执行，如有报错请贴出报错信息

**Comment by Ludovicofu** [comment]
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 95, in create_connection
  File "urllib3\util\connection.py", line 85, in create_connection
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 363, in connect
  File "urllib3\connection.py", line 179, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000299A823BB80>, 'Connection to api.github.com timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/xzajyjs/ThunderSearch/releases/latest (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000299A823BB80>, 'Connection to api.github.com timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ThunderSearch.py", line 54, in checkUpdate
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 507, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/xzajyjs/ThunderSearch/releases/latest (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000299A823BB80>, 'Connection to api.github.com timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ThunderSearch.py", line 1130, in <module>
  File "ThunderSearch.py", line 49, in __init__
  File "ThunderSearch.py", line 60, in checkUpdate
UnboundLocalError: local variable 'resp' referenced before assignment

**Comment by xzajyjs** [comment]
注释line49， 下个版本修复
